#!/bin/bash

#> [name]=? [org]=?

if [[ "$NAME" == "main" ]]; then
 K3NAME="$ORG"
else
 K3NAME="$NAME-$ORG"
fi

with lxc delete vm --name $NAME --org $ORG
dns_delete_record $K3NAME kueb.io
rm /etc/traefik/services/${K3NAME}.yaml
rm /etc/traefik/services/${K3NAME}-6443.yaml