#!/bin/bash

#> [name]=? [org]=?

VMNAME="$NAME-$ORG"

with lxc delete vm --name $NAME --org $ORG
dns_delete_record $VMNAME kueb.io
rm /etc/traefik/services/${VMNAME}.yaml
rm /etc/traefik/services/${VMNAME}-6443.yaml