#!/bin/bash

#> [name]=? [org]=?

VMNAME="$NAME-$ORG"
if [[ "$NAME" == "main" ]]; then
 K3NAME="$ORG"
else
 K3NAME="$NAME-$ORG"
fi

lxc stop $VMNAME
lxc delete $VMNAME
dns_delete_record $K3NAME kueb.io
rm /etc/traefik/services/${K3NAME}.yaml
rm /etc/traefik/services/${K3NAME}-6443.yaml