#!/bin/bash

#> [name]=some [org]=?

VMNAME="$NAME-$ORG"

lxc config show $VMNAME > /dev/null 2>&1
if [ $? -eq 0 ]; then
  lxc stop $VMNAME
  lxc delete $VMNAME
  store_delete_vm $VMNAME
  echo "Container $VMNAME was removed"
else
  echo "Container $VMNAME not found"
fi