#!/bin/bash

#> [name]=sys-main

STEP=1
for host in fs1701 fs1702 fs1703; do
  HOSTNAME=$host.pilet.cloud
  ssh -t root@${HOSTNAME} bash -l -c "'with lxc delete vm --name ${NAME}-${STEP}'"
  STEP=$((STEP+1))
done
