#!/bin/bash

#>

cat <<EOF | store_sys
DROP SCHEMA IF EXISTS system CASCADE;
CREATE SCHEMA system;
SET search_path to system;

CREATE TABLE host (
  host TEXT PRIMARY KEY,
  ram INT,
  cpu INT,
  disk INT
);

CREATE TABLE net4 (
  id TEXT GENERATED ALWAYS AS ( left(md5(type||host),4) ) STORED,
  type TEXT default 'public',
  host TEXT REFERENCES host,
  address TEXT,
  subnet INT default 32,
  template TEXT default 'none',
  PRIMARY KEY (id)
);

CREATE TABLE net6 (
  id TEXT GENERATED ALWAYS AS ( left(md5(type||host),4) ) STORED,
  type TEXT default 'public',
  host TEXT REFERENCES host,
  address TEXT,
  subnet INT default 64,
  template TEXT default 'none',
  PRIMARY KEY (id)
);

INSERT INTO host (host,ram,cpu,disk) VALUES
('fs1701.pilet.cloud', 128, 32, 6000),
('fs1702.pilet.cloud', 128, 32, 6000),
('fs1703.pilet.cloud', 128, 32, 6000);

INSERT INTO net4 (host,address) VALUES
('fs1701.pilet.cloud', '142.132.204.215'),
('fs1702.pilet.cloud', '142.132.206.130'),
('fs1703.pilet.cloud', '94.130.54.233');

INSERT INTO net4 (type,host,address,subnet,template) VALUES
('vm','fs1701.pilet.cloud', '192.168.1.1', 16, '192.168.1.*'),
('vm','fs1702.pilet.cloud', '192.168.2.1', 16, '192.168.2.*'),
('vm','fs1703.pilet.cloud', '192.168.3.1', 16, '192.168.3.*');

INSERT INTO net6 (host,address,template) VALUES
('fs1701.pilet.cloud', '2a01:4f8:261:5103::2','2a01:4f8:261:5103::*'),
('fs1702.pilet.cloud', '2a01:4f8:261:52da::2','2a01:4f8:261:52da::*'),
('fs1703.pilet.cloud', '2a01:4f8:10b:2c49::2','2a01:4f8:10b:2c49::*');

EOF