#!/bin/bash

#> [hostname]=?

#hostnamectl set-hostname $HOSTNAME

apt update >/dev/null
apt install -y apt-transport-https ca-certificates curl software-properties-common jq >/dev/null

#apt install -y snapd
#snap install yq


