#!/bin/bash

#> [hostname]=?

hostnamectl set-hostname $HOSTNAME

apt update
apt install -y apt-transport-https ca-certificates curl software-properties-common jq snapd zfsutils-linux
snap install yq
snap install lxd

apt install python3
apt install python3-pip
pip install rsa
