#!/bin/bash

#> [name]=sys-main

MASTER=$(with store get value --key ${NAME}/ip4)
TOKEN=$(with store get value --key ${NAME}/token)

lxc exec $NAME -- K3S_URL=https://${MASTER}:6443 K3S_TOKEN=${TOKEN} /root/cli/scripts/k3s-install.sh