#!/bin/bash

#> [name]=sys-main

lxc exec $NAME -- /root/cli/scripts/k3s-install.sh

#TOKEN=$(lxc exec uno -- cat /var/lib/rancher/k3s/server/token)
#with store set value --key ${NAME}.token --value $TOKEN


