#!/bin/bash

#> [name]=sys-main

IP6=$(store_get_vm_addr6 $NAME)
lxc exec $NAME -- bash -c "INSTALL_K3S_EXEC='server --tls-san ${NAME}.pilet.site --node-ip ${IP6} --cluster-cidr 2001:cafe:42:0::/56 --service-cidr 2001:cafe:43:1::/112' /root/cli/scripts/k3s-install.sh"

TOKEN=$(lxc exec $NAME -- cat /var/lib/rancher/k3s/server/token)
IP4=$(store_get_vm_addr4 $NAME)
with store set value --key ${NAME}/token --value $TOKEN
with store set value --key ${NAME}/ip4 --value $IP4