#!/bin/bash

#> [name]=sys-main

IP6=$(store_get_vm_addr4 $NAME)

cat<<EOF | lxc shell $NAME
INSTALL_K3S_EXEC="server --node-ip ${IP6} --cluster-cidr 2001:cafe:42:0::/56 --service-cidr 2001:cafe:43:1::/112" /root/cli/scripts/k3s-install.sh
EOF

TOKEN=$(lxc exec $NAME -- cat /var/lib/rancher/k3s/server/token)
with store set value --key ${NAME}/token --value $TOKEN
with store set value --key ${NAME}/ip6 --value $IP6