#!/bin/bash

#> [name]=sys-main [cluster]=?

MASTER=$(with store get value --key ${CLUSTER}/ip6)
TOKEN=$(with store get value --key ${CLUSTER}/token)
IP6=$(store_get_vm_addr6 $NAME)

INSTALL_K3S_EXEC="agent --server=https://${MASTER}:6443/  --node-ip ${IP6} --token=${TOKEN}"

lxc exec $NAME -- bash -l -c "INSTALL_K3S_EXEC=\"${INSTALL_K3S_EXEC}\" /root/cli/scripts/k3s-install.sh"
