#!/bin/bash

#>

mkdir -p /etc/traefik/services
cat <<EOF > /etc/traefik/traefik.yaml
## Static configuration
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  k8s:
    address: ":6443"

certificatesResolvers:
  resolver0:
    acme:
      email: "potapov@yahoo.com"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  file:
    directory: /etc/traefik/services
    watch: true
EOF

FILENAME=traefik_v3.2.3_linux_$(dpkg --print-architecture).tar.gz
wget https://github.com/traefik/traefik/releases/download/v3.2.3/$FILENAME
tar xzvf $FILENAME -C /tmp
mv /tmp/traefik /usr/local/bin
rm $FILENAME
