#!/bin/bash

#>

ufw enable
ufw allow ssh
ufw allow https
ufw allow 6443

ufw deny out to 10.0.0.0/8
ufw deny out to 172.16.0.0/12
ufw deny out to 192.168.0.0/24

ufw allow in on br0
ufw route allow in on br0
ufw route allow out on br0