#!/bin/bash

#> [type]=public [host]=? [address]=? [subnet]=32 [template]=none

NAME=$(echo -n "$TYPE,$KIND,$HOST" | md5sum)

cat <<EOF | store_sys
INSERT INTO system.net(name, type, kind, host, address, subnet, template)
VALUES ('$NAME','$TYPE',4,'$HOST','$ADDRESS',$SUBNET,'$TEMPLATE');
EOF