#!/bin/bash

#> [type]=public [host]=? [address]=? [subnet]=64 [template]=none

NAME=$(echo -n "$TYPE,$KIND,$HOST" | md5sum)
NAME=${NAME:0:4}

cat <<EOF | store_sys
INSERT INTO system.net(name, type, kind, host, address, subnet, template)
VALUES ('$NAME','$TYPE',6,'$HOST','$ADDRESS',$SUBNET,'$TEMPLATE');
EOF