#!/bin/bash

#> [name]=? [profile]=lg

with lxc create vm --name $NAME --profile $PROFILE
if [ $? -ne 0 ]; then
  echo "Failed creating container $NAME"
  exit 1
fi

with lxc install k3s-master --name $NAME

IPV4=$(store_get_vm_addr4 $NAME)
dns_create_record CNAME $NAME pilet.site $SYS_HOSTNAME

cat <<EOF > /etc/traefik/services/${NAME}.yaml
http:
  routers:
    route-$NAME:
      rule: "Host(\`${NAME}.pilet.site\`)"
      tls:
        certResolver: resolver0
        domains:
          - main: "*.pilet.site"
      service: service-$NAME
      priority: 1000
      entryPoints:
        - https

  services:
    service-$NAME:
      loadBalancer:
        servers:
          - url: "http://${IPV4}:80"
EOF

cat <<EOF > /etc/traefik/services/${NAME}-6443.yaml
tcp:
  routers:
    route-$NAME-k8s:
      rule: "HostSNI(\`${NAME}.pilet.site\`)"
      tls:
        passthrough: true
      service: service-$NAME-k8s
      priority: 1000
      entryPoints:
        - k8s

  services:
    service-$NAME-k8s:
      loadBalancer:
        servers:
          - address: "${IPV4}:6443"
EOF


