#!/bin/bash

#> [name]=some

with lxc create vm --name $NAME --profile md
if [ $? -ne 0 ]; then
  echo "Failed creating container $NAME"
  exit 1
fi

cat <<EOF | lxc shell $NAME
apt update
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 --service-cidr=10.43.0.0/16,2001:cafe:43::/112" sh -s -
EOF

echo "Kubernetes master $NAME is created"


