#!/bin/bash

#> [name]=some

with lxc create vm --name $NAME --profile md
if [ $? -ne 0 ]; then
  echo "Failed creating container $NAME"
  exit 1
fi

cat <<EOF | lxc shell $NAME
apt update
ufw disable
ufw allow 6443/tcp #apiserver
ufw allow from 10.42.0.0/16 to any #pods
ufw allow from 10.43.0.0/16 to any #services

curl -sfL https://get.k3s.io | sh -
EOF

echo "Kubernetes master $NAME is created"


