#!/bin/bash

#> [name]=? [org]=? [profile]=medium [zone]=kueb.link

if [[ "$NAME" == "main" ]]; then
 VMNAME="$ORG"
else
 VMNAME="$NAME-$ORG"
fi

with lxc create vm --name $NAME --org $ORG --profile $PROFILE
if [ $? -ne 0 ]; then
  echo "Failed creating container $VMNAME"
  exit 1
fi

lxc exec $VMNAME -- bash -c "/root/cli/with host setup kube --hostname ${VMNAME}.${ZONE}"