#!/bin/bash

#> [name]=? [org]=? [profile]=medium

if [[ "$NAME" == "main" ]]; then
 VMNAME="$ORG"
else
 VMNAME="$NAME-$ORG"
fi

with lxc create vm --name $NAME --org $ORG --profile $PROFILE
if [ $? -ne 0 ]; then
  echo "Failed creating container $VMNAME"
  exit 1
fi

IP6=$(store_get_vm_addr6 $VMNAME)
lxc exec $VMNAME -- bash -c "/root/cli/with host setup kube --hostname ${VMNAME}.kueb.link"