#!/bin/bash

#> [name]=some [profile]=md

lxc config show $NAME > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Container $NAME already exists"
  exit 1
fi

OPTIONS="--profile base"
for profile in ${PROFILE/,/ }; do
  OPTIONS="$OPTIONS --profile $profile"
done

echo "Running lxc init"
lxc init ubuntu:24.04 $NAME --vm $OPTIONS
echo "Running lxc start"
lxc start $NAME

while true; do
  echo "Waiting 2s"
  sleep 2s
  IPV6=$(lxc exec $NAME ip addr 2>/dev/null | grep 2a01 | awk '{print $2}')
  IPV4=$(lxc exec $NAME ip addr 2>/dev/null | grep 'inet 10' | awk '{print $2}')
  echo -n "."
  IPV6=${IPV6/\/64/}
  IPV4=${IPV4/\/24/}
  if [ ! -z "$IPV6" ]; then
    echo ""
    echo "IPs are $IPV4, $IPV6"
    store_save_vm $NAME $PROFILE $IPV4 $IPV6
    echo ""
    break
  fi
done

while true; do
  DONE=$(lxc exec $NAME -- cat /root/.done 2>/dev/null)
  if [[ "$DONE" == "done" ]]; then
    echo "Done"
    break
  fi
  echo -n "."
  sleep 2s
done