#!/bin/bash

#> [name]=? [profiles]=md

OPTIONS=""
for profile in ${PROFILES/,/ }; do
  OPTIONS="$OPTIONS --profile $profile"
done

echo "Initializing $NAME with $OPTIONS"
lxc init ubuntu:24.04 $NAME $OPTIONS
store_vm_add $NAME $PROFILES
lxc start $NAME

while true; do
  sleep 1s
  IPV6=$(lxc exec $NAME ip addr | grep 2a01 | awk '{print $2}')
  IPV4=$(lxc exec $NAME ip addr | grep 192. | awk '{print $2}')
  IPV6=${IPV6/\/64/}
  IPV4=${IPV4/\/16/}
  if [ ! -z "$IPV6" ] && [ ! -z "$IPV4" ]; then
    echo "ipv4 is $IPV4 and ipv6 is $IPV6"
    break
  fi
done