#!/bin/bash

# ID
function store_post() {
  curl -H "Content-Type: application/json" -X POST --data-binary @- https://main.pilet.site/v1/store/json/$1
}

# ID
function store_delete() {
  curl -X DELETE https://main.pilet.site/v1/store/json/$1
}

# NAME PROFILE IP4 IP6
function store_save_vm() {
  NAME=$1
  PROFILE=$2
  IP4=$3
  IP6=$4
  cat <<-EOF | store_post infra/hosts/$SYS_HOSTNAME/vms/$NAME
      {
        "profile": "$PROFILE",
        "ip4": "$IP4",
        "ip6": "$IP6"
      }
EOF
}

# NAME
function store_delete_vm() {
  NAME=$1
  store_delete infra/hosts/$SYS_HOSTNAME/vms/$NAME
}


# store_get_vm_addr4 NAME
function store_get_vm_addr4() {
  echo "SELECT ipv4 FROM system.vm WHERE \
  host = '$SYS_HOSTNAME' AND name = '$1'  " | store_sys_csv
}

# store_get_vm_addr6 NAME
function store_get_vm_addr6() {
  echo "SELECT ipv6 FROM system.vm WHERE \
  host = '$SYS_HOSTNAME' AND name = '$1'  " | store_sys_csv
}


# store_vm_addr4 NAME HOST
function store_vm_addr4() {
  echo "SELECT ipv4 FROM system.vm WHERE \
  host = '$2' AND name = '$1'  " | store_sys_csv
}

function store_kv_set() {
  KEY=$1
  VALUE=$2
  echo "INSERT INTO system.kv (id,value) VALUES('$KEY','$VALUE') ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value" | store_sys
}

function store_kv_get() {
  KEY=$1
  echo "SELECT value FROM system.kv WHERE id = '$KEY'" | store_sys_csv
}

