#!/bin/bash

# ID
function store_post() {
  curl -H "Content-Type: application/json" -X POST --data-binary @- https://main.pilet.site/v1/store/json/$1
}

# ID
function store_yaml_post() {
  curl -H "Content-Type: application/yaml" -X POST --data-binary @- https://main.pilet.site/v1/store/yaml/$1
}

# ID
function store_get() {
  curl https://main.pilet.site/v1/store/json/$1
}

# ID
function store_yaml_get() {
  curl https://main.pilet.site/v1/store/yaml/$1
}


# ID
function store_delete() {
  curl -X DELETE https://main.pilet.site/v1/store/json/$1
}

# NAME PROFILE IP4 IP6
function store_save_vm() {
  NAME=$1
  PROFILE=$2
  IP4=$3
  IP6=$4
  cat <<-EOF | store_post infra/hosts/$SYS_HOSTNAME/vms/$NAME
      {
        "profile": "$PROFILE",
        "ip4": "$IP4",
        "ip6": "$IP6"
      }
EOF
}

# NAME
function store_delete_vm() {
  NAME=$1
  store_delete infra/hosts/$SYS_HOSTNAME/vms/$NAME
}


# store_get_vm_addr4 NAME
function store_get_vm_addr4() {
  NAME=$1
  store_get infra/hosts/$SYS_HOSTNAME/vms/$NAME | jq -r .ip4
}

# store_get_vm_addr6 NAME
function store_get_vm_addr6() {
  NAME=$1
  store_get infra/hosts/$SYS_HOSTNAME/vms/$NAME | jq -r .ip6
}

