#!/bin/bash

function store_sys() {
  psql -U pilet -h pg.pilet.site -d system
}

function store_sys_csv() {
  psql -U pilet -h pg.pilet.site -d system --csv -t
}

function store_vm_add() {
  # store_vm_add name profiles
  echo "SELECT system.add_vm('$SYS_HOSTNAME','$1','$2')" | store_sys_csv
}