#!/bin/bash

#>

apt update && sudo apt upgrade -y
apt install -y docker.io

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

apt update
apt install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

kubeadm init --pod-network-cidr=10.244.0.0/16

echo 'export KUBECONFIG=/etc/kubernetes/admin.conf' >> ~/.profile