#!/bin/bash

#>

IP6=$(ip addr | grep 2a01: | grep /128 | awk '{print $2}')
IP6="${IP6/\/128/\/64}"

echo "ip6 : ${IP6}"
#lxc network create br0 --type bridge
cat <<EOF #| lxc network edit br0
name: br0
description: "Br0 default"
config:
  ipv4.address: 10.224.181.1/24
  ipv4.nat: "true"
  ipv6.address: 2a01:4f8:261:52da::2/64
  ipv6.nat: "true"
EOF