#!/bin/bash

#> 

vm_save_uno_profile 1 4 140 sm
vm_save_uno_profile 2 8 280 md
vm_save_uno_profile 4 16 560 lg
vm_save_uno_profile 8 32 1180 xl
vm_save_uno_profile 16 64 2360 xxl

vm_save_profile_base
vm_save_profile_vlan


