#!/bin/bash

#> [name]=sys-main [profile]=lg,vlan

#with multi create vm --name $NAME --profile $PROFILE

cat <<EOF | ssh root@fs1701.pilet.cloud
lxc exec $NAME -- /root/cli/scripts/k3s-install.sh
EOF

#ssh -t root@fs1702.pilet.cloud bash -l -c "'with lxc install k3s-node --name $NAME --cluster $NAME'"
#ssh -t root@fs1703.pilet.cloud bash -l -c "'with lxc install k3s-node --name $NAME --cluster $NAME'"
