#!/bin/bash

#> [name]=sys-main [profile]=lg

STEP=1
for host in fs1701 fs1702 fs1703; do
  HOSTNAME=$host.pilet.cloud
  ssh -t root@${HOSTNAME} bash -l -c "'with lxc create vm --name ${NAME}-${STEP} --profile $PROFILE"
  if [[ "$host" == "fs1701" ]]; then
    ssh -t root@${HOSTNAME} bash -l -c "'with lxc install k6s-master --name ${NAME}-${STEP}'"
    sleep 10s
  else
    ssh -t root@${HOSTNAME} bash -l -c "'with lxc install k6s-node --name ${NAME}-${STEP} --cluster ${NAME}-1'"
  fi
  STEP=$((STEP+1))
done

#with multi create vm --name $NAME --profile $PROFILE

#ssh -t root@fs1701.pilet.cloud bash -l -c "'with lxc install k6s-master --name $NAME'"
#ssh -t root@fs1702.pilet.cloud bash -l -c "'with lxc install k6s-node --name $NAME --cluster $NAME'"
#ssh -t root@fs1703.pilet.cloud bash -l -c "'with lxc install k6s-node --name $NAME --cluster $NAME'"
