#!/bin/bash

#>

lxc profile create vlan

cat <<EOF | lxc profile edit vlan
name: vlan
description: vlan bound
config: {}
devices:
  enp6s0:
    name: enp6s0
    nictype: bridged
    parent: vlan0
    type: nic
used_by: []
EOF
